/**
 * Generates a companion GDScript file that wires GduiActionRouter
 * for all `action` attributes found in the compiled scene AST.
 *
 * The generated file is a starting template — developers are expected
 * to add actual handler logic to each match branch.
 */

/**
 * @param {object} sceneAst  Normalized scene AST (output of normalizeToSceneAst)
 * @param {object} [options]
 * @param {string} [options.sourceName]  Original .gdui.html filename (for header comment)
 * @returns {{ content: string, actions: string[] }}
 */
export function generateActionScript(sceneAst, options = {}) {
  const actions = collectActions(sceneAst);
  const sourceName = options.sourceName || `${sceneAst.name}.gdui.html`;
  const content = buildScript(sceneAst, actions, sourceName);
  return { content, actions };
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

function collectActions(node, found = new Set()) {
  if (node.attrs?.action) found.add(node.attrs.action);
  for (const child of node.children || []) {
    collectActions(child, found);
  }
  return [...found].sort();
}

function rootExtends(sceneAst) {
  // gd-screen maps to Control; other roots are rare but handled generically
  const typeMap = {
    Control: "Control",
    Panel: "Panel",
    Node: "Node",
  };
  return typeMap[sceneAst.type] ?? "Control";
}

function buildScript(sceneAst, actions, sourceName) {
  const lines = [];
  const ext = rootExtends(sceneAst);
  const hasActions = actions.length > 0;

  lines.push(`# Generated by GDUI — feel free to edit`);
  lines.push(`# Source: ${sourceName}`);
  lines.push(`extends ${ext}`);
  lines.push(``);

  if (hasActions) {
    lines.push(
      `const _ROUTER_SCRIPT := preload("res://addons/gdui/runtime/action_router.gd")`,
    );
    lines.push(``);
    lines.push(`var _router: GduiActionRouter`);
    lines.push(``);
  }

  lines.push(`func _ready() -> void:`);

  if (hasActions) {
    lines.push(`\t_router = _ROUTER_SCRIPT.new()`);
    lines.push(`\tadd_child(_router)`);
    lines.push(`\t_router.action_triggered.connect(_on_gdui_action)`);
    lines.push(`\t_router.connect_actions(self)`);
  } else {
    lines.push(`\tpass`);
  }

  if (hasActions) {
    lines.push(``);
    lines.push(
      `func _on_gdui_action(action: String, source: Node, _meta: Dictionary) -> void:`,
    );
    lines.push(`\tmatch action:`);

    for (const action of actions) {
      lines.push(`\t\t"${action}":`);
      lines.push(`\t\t\tpass  # TODO: handle ${action}`);
    }

    lines.push(`\t\t_:`);
    lines.push(
      `\t\t\tpush_warning("GduiActions: unhandled action '%s'" % action)`,
    );
  }

  lines.push(``);
  return lines.join("\n");
}
